### ISSUE TITLE
Fullscreen shortcut flips the images

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#105]
The `openseadragon` has a default shortcut key to toggle flip state of the image.
We don't need this and has conflicts with the full screen shortcut.`f`.

**Comment by Dan2D** [comment]
I'll give this one a shot

**Comment by Dan2D** [comment]
So, openseadragon uses switch cases for the keypress events.
The only way I found to change it was to manually change the keypress case from 102 ( f ) to something like 109 (m, for mirror?).

The problem with this, is that anytime you want to update the seadragon package, this code will be overwritten.

Alternatively, you could change your keyboard shortfuct for full screen from 'f' to something else.

Wanted to see what your thoughts on this were before submitting the PR.

**Comment by Dan2D** [comment]
Also, you could add event.preventDefault(); under your 'f' key press event, but you'd need to make a new function for flipping the canvas.

**Comment by btzr-io** [comment]
I guess addign `event.preventDefault()` is the best option for now, I'll check the openseadragon repo to see if ther is more information.
