### ISSUE TITLE
Slider handler component displayed behind slider-track

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#109]
The handler of the slider is displayed behind the slider track component it should be the other way around (handler always on the front)

> Note: They have the same background color so is hard to see on the screen

**Comment by hugonxc** [comment]
Could you please assign me this?

**Comment by btzr-io** [comment]
@hugonxc  no need to assing`, just leave a comment that you are working on it ^^

**Comment by hugonxc** [comment]
Awesome... so I'm working on.

**Comment by btzr-io** [comment]
Not sure if this was introduced on: https://github.com/btzr-io/Villain/commit/36190013de45acecaf4a807788d9045f36cd3ea4, but it maybe good to look at it.

Let me know if you have any questions :v:

**Comment by hugonxc** [comment]
@btzr-io I think this issue is already solved by the commit you tagged.

![slider](https://user-images.githubusercontent.com/10819341/67320169-3460f100-f4e4-11e9-9a49-961035808b07.png)

**Comment by btzr-io** [comment]
@hugonxc  please read the note: mentioned on the issue description

**Comment by btzr-io** [comment]
> Note: They have the same background color so is hard to see on the screen

you will need to change the colors to see  the bug.
