### ISSUE TITLE
Fix fullscreen mode

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#11]
The current fullscreen mode only expands the size of the viewer, it should actually trigger the fullscreen enter / exit event of the window.

Use the `lib/full-screen.js` polyfill.

**Comment by vclayton** [comment]
I'd like to see if I can get this to work.

**Comment by btzr-io** [comment]
@vclayton sure go for it.

**Comment by btzr-io** [comment]
Fixed by https://github.com/btzr-io/Villain/commit/af45d1e3bc1db2ab0816a27bad445b1d5fb7d2ab
