### ISSUE TITLE
Improve language selector

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#110]
The current component takes alot of space on the toolbar, lags of appropiate styles and needs to follow the The W3C Web Accessibility Initiative (WAI) .

Should probably be moved to a inside a menu component: see #13

**Comment by seal62** [comment]
Hi @btzr-io please assign to me and I will do this for you

**Comment by seal62** [comment]
Hey @btzr-io when you say the selector 'takes alot of space on the toolbar', do you have any suggestions in mind on how to reduce this? The way I see it, there are a few options. Remove the icon, stack the icon on top of the selector (this might look strange though), or reduce the size of the icon and selector (probably least impact on overall size). which would you prefer?

**Comment by seal62** [comment]
before I create a PR, here is a commit without size changes. just added WAI and styling
https://github.com/seal62/Villain/commit/bb8289163e2733f4e64af35360e0a454dc3835d2

**Comment by btzr-io** [comment]
I would prefer not to use an icon at all, this is an advance feature and it should be hidden or at least not present direclty on the toolbar (it should be just for navigation / zoom controls and probably layout mode )
> Should probably be moved to a inside a menu component: see #13

**Comment by btzr-io** [comment]
@seal62 But I guess those changes are great for now, can you post a screen preview and open a `pr` ?

**Comment by seal62** [comment]
Created PR, screenshot attached

<img width="1244" alt="Screenshot 2019-10-24 at 17 08 17" src="https://user-images.githubusercontent.com/5068912/67458136-2694a280-f681-11e9-86e5-cedc53c36dce.png">
