### ISSUE TITLE
Tooltip for slider handler

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#119]
The slider handler component needs a tool tooltip display the new value that will be selected:
- It should show / hide on `mouse-over` like a normal tooltip but also while user is dragging / moving the handler.

> Note: The tooltip was removed on https://github.com/btzr-io/Villain/commit/24c9e32fb21ad7a82fc0fc22fa6fd11fd4854fa5  because it was causing alot of issues: https://github.com/btzr-io/Villain/issues/103 https://github.com/btzr-io/Villain/issues/112

**Comment by ThomasLuu00** [comment]
I would like to work on this issue.

**Comment by fuku710** [comment]
Thanks @ThomasLuu00 .
I made previous PR about tooltip (#111,#115) .
I may help if you need.

**Comment by btzr-io** [comment]
Check this examples: https://sghall.github.io/react-compound-slider/#/slider-demos/tooltips
