### ISSUE TITLE
Improve tooltips for controls

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#12]
- [ ] Buttons and other interactive elements are missing tooltips.
- [ ] Better tooltip messages

~We should also look for a react component instead of using the native tooltips.~
I think we should stick for the native ones for know but open for suggestions.

**Comment by n1tin** [comment]
Hey! Would be interested in looking at https://github.com/bsidelinger912/react-tooltip-lite. It is used in one of the projects at my workplace and looks neater than the 'react-tooltip' lib. Also if you are fine with this I can work to raise a PR with the tooltip changes for the elements where ever you think it is required.

**Comment by btzr-io** [comment]
@n1tin  Sure, go for it :+1:

**Comment by btzr-io** [comment]
Some examples and suggestions:
https://material.io/components/tooltips/#

**Comment by btzr-io** [comment]
@n1tin Are you still working on this ?

**Comment by n1tin** [comment]
Yes @btzr-io. I have made some changes (https://github.com/n1tin/Villain/commit/0a1179ce7456a51956533a21ba40a5a2acf7e61b) but it is not working properly in the fullscreen mode so trying to fix that.

**Comment by btzr-io** [comment]
@n1tin Oh ok, just checking,
Well if you have any questions or need help let me know :v:

**Comment by n1tin** [comment]
'react-tooltip-lite' lib is adding the tooltip `<span>` outside the `App` container tag so I am having to move css variables to `:root`. Are you okay with this or are you preferring the native ones?

**Comment by btzr-io** [comment]
@n1tin I guess its ok to move them to `:root` but maybe we should add a prefix to prevent conflicts with external styles? like this:
```
--villain-toolbar-bg: #FFF;
```

Anyway don't worry about it, should be handle on a different `pr` unless you also want to work on that?

**Comment by n1tin** [comment]
Will get the tooltip working first 🙂

**Comment by n1tin** [comment]
@btzr-io Have raised https://github.com/btzr-io/Villain/pull/75. Have added a native tooltip one as all the libs I tried are rendering outside of the `app` div and it is not working in fullscreen as the main content is taking up the screen and nothing outside of it can be made visible.
