### ISSUE TITLE
Localize error messages

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#121]
Use the new `@/localize` implementation to localize all the error `strings`: 
```
"Some string" -->  Localize["Some string"]
```

Also add / update the missing strings on  `./locales`

See: Localization #76

**Comment by minmaxdata** [comment]
can I take this? my first contribution.

**Comment by lucas-barros** [comment]
@btzr-io I'm working on this, ok?

**Comment by lucas-barros** [comment]
I opened the PR https://github.com/btzr-io/Villain/pull/123
