### ISSUE TITLE
Manga mode ignores current page

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#124]
When switching to manga mode the current page gets a reset and jumps to the first page, it should remain the same.

Also it should trigger `renderPages()` to fix the position on book mode

### Update
> looks like it only happens when you drag the slider, don't use the buttons, also book mode is not showing the inverted layout until you change the page again.

See: https://github.com/btzr-io/Villain/issues/124#issuecomment-545524282

**Comment by btzr-io** [comment]
@maydayo any ideas ?

**Comment by btzr-io** [comment]
The issue appears to be coming from the onChange function of the slider `component`

**Comment by maydayo** [comment]
It seems to be working fine on my laptop. 🤔
![ezgif-1-9f6127a19c90](https://user-images.githubusercontent.com/22811877/67362981-9843f200-f596-11e9-8c3b-5f796064cfdb.gif)

**Comment by btzr-io** [comment]
@maydayo looks like it only happens when you drag the slider, don't use the buttons
