### ISSUE TITLE
Create dark theme for the example demo

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#126]
Create a dark theme for the example demo:

- Should toggle with the theme selector component.
- Check the viewer dark theme for inspiration.

Also check: Theme selector on the example demo dont work #127

**Comment by nik72619c** [comment]
I'll give it a try

**Comment by btzr-io** [comment]
For the example page (that includes the sidebar)

**Comment by nik72619c** [comment]
so its the <demo/> right ? I hope I'm not missing anything

**Comment by btzr-io** [comment]
yes here: https://github.com/btzr-io/Villain/tree/master/examples

**Comment by nik72619c** [comment]
okay, thanks a lot :)

**Comment by nik72619c** [comment]
ref #168 @btzr-io , please have a look and suggest changes if any.
