### ISSUE TITLE
Theme selector on the example demo dont work

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#127]
The theme selector on the example demo should toggle the theme state of the component.

**Comment by ismaeldcom** [comment]
In case it helps, I checked it while developed the demo and the component receives all the new props but don't update. The same apply for #125. In the theme case I think it might be because the component read the context and not the prop.

**Comment by btzr-io** [comment]
Fixed on: https://github.com/btzr-io/Villain/commit/fe2c311b2e1fb60c1c489366fdefce7d0f4d4a53
