### ISSUE TITLE
Menu (options)

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#13]
The space of the toolbar is limited, we will eventually need panel or drop menu to display all the configurable options of the player.

> Note always keep in mind usability and accessibility :v:

**Comment by Deepam101** [comment]
The navigation buttons should be in the middle and the other buttons can be better arranged.Can you assign this?

**Comment by btzr-io** [comment]
@Deepam101 Why  in the middle ? I don't think the main problem is that there is not enough space, and we dont need to show some of the buttons, like the theme, language and probably the manga mode should exist on other component. 

No need to assign just leave a comment that you are working on it :v:

**Comment by Deepam101** [comment]
@btzr-io Got it...but can you elaborate what's page rotation?

**Comment by btzr-io** [comment]
@Deepam101 Buttons to rotate the images :upside_down_face:
