### ISSUE TITLE
Can't type or interact with zoom input

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#131]
The zoom input on the toolbar don't allow to type or the value is not updating for some reason.
Probably caused by the `getDerivatedStateFromProps` implementation.

We should be able to change the zoom levels by typing the number.

**Comment by cesar-cb** [comment]
Hey, can I take this issue ?

**Comment by btzr-io** [comment]
@cesar-cb sure :+1:

**Comment by btzr-io** [comment]
@cesar-cb are you still working on this ?

**Comment by cesar-cb** [comment]
@btzr-io, I was going to look this issue today, but you can merge @jenniferharmon PR, I will look into another issue
