### ISSUE TITLE
Reduce components updates

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#135]
We should prevent unnecessary component updates by using `PureComponent` or `React.memo` whenever is possible.

### Notes

> I don't think we should switch all components to `PureComponents` at least at once.
I suggest to just start with the simple ones, to make sure we don't break anything and that there is an actual performance benefit.

> Also we we are rewriting some of them to `functional` components : see https://github.com/btzr-io/Villain/issues/136

**Comment by linsuri** [comment]
I will take this.

**Comment by Sonam3107** [comment]
Can I give this a try?
