### ISSUE TITLE
Css styles refactoring

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#140]
- [x] Add `villain` prefix
- [x] Clear  / tidy ip css styles.
- [x] Remove unused css styles / classes.
- [x] Better naming convention for classes.
- [x] Simplify styles.
- [x]  Split main css into different files for each component #99

**Comment by abbasCoder51** [comment]
@btzr-io can I have a go at this please?

**Comment by btzr-io** [comment]
@abbasCoder51  sure

**Comment by abbasCoder51** [comment]
@btzr-io #160

**Comment by abbasCoder51** [comment]
@btzr-io #175
