### ISSUE TITLE
Controls always hide on fullscreen

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#141]
The `autoHideControls` feature is not working properly on fullscreen mode.
When setting the pin button to false it will hide the controls and they wont show anymore.

Also this needs some improvement to handle show / hide interactions on fullscreen mode

**Comment by kamilszmajdzinski** [comment]
I'm taking this one 🤓

**Comment by kamilszmajdzinski** [comment]
Fix: https://github.com/btzr-io/Villain/pull/147
