### ISSUE TITLE
Tooltip hide / show fails

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#164]
- If you move the mouse really fast on the toolbar sometimes the `tooltip` just stays there and doesn't hide. ~Not sure if this is also a bug on chrome.~

- Full screen tooltip doesn't hide when enter / exit  fullscreen mode.

Please consider this as a solution: https://github.com/btzr-io/Villain/issues/163

**Comment by anusha5695** [comment]
Hi I would like to work on this

**Comment by btzr-io** [comment]
@anusha5695 Sure

**Comment by anusha5695** [comment]
@btzr-io : Sure 👍

**Comment by btzr-io** [comment]
Fixed by https://github.com/btzr-io/Villain/commit/ef517acf9f8c219676e81439b3110ec7e6f5379f
