### ISSUE TITLE
Implement reakit 

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#165]
Creating core components like buttons and tooltip is becoming hard to maintain and takes a lot of time to integrate accessibility (WIA-ARIA standars):

- [x] Buttons
- [x] Tooltips #163
- [x] Checkbox
- [x] Toolbar
- [ ] Text inputs
- [ ] Numeric inputs
- [ ] Selectors ( Dropdown menu )
- [x] Menu #13

We should use an existent solution to handle this, right now `reakit` seems the way to go, but I'm open for ideas.

See: https://github.com/reakit/reakit

> :warning:  Note: if you want to help with this issue feel free to open one pull request peer component at a time. Multiple pr accepted.

**Comment by Tarektouati** [comment]
i'll do it , can you assign me to this ?

**Comment by btzr-io** [comment]
@Tarektouati sure :+1:

**Comment by btzr-io** [comment]
Please read the note at the bottom ^^

**Comment by btzr-io** [comment]
@Tarektouati Let me know if you have any questions :v:

**Comment by Tarektouati** [comment]
@Btz-io okay i’ll do a PR components 😊

**Comment by btzr-io** [comment]
@Tarektouati I did some progress with the menu, `tooltips` are a priority due the current component causing alot of issues, let me know if you can start with that :v:

**Comment by Tarektouati** [comment]
@btzr-io Yes of course, i'll start with tooltips refacto today !

**Comment by Tarektouati** [comment]
@btzr-io  I've submitted a PR waiting for review pls , let me know if i did something wrong before i start working on an other component 😄

**Comment by btzr-io** [comment]
Update on tooltip, see: https://github.com/btzr-io/Villain/pull/185#issuecomment-547247082
