### ISSUE TITLE
Change fullscreen icon on enter and exit events

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#17]
When entering and leaving fullscreen the icon of the button should also change.

**Comment by fllprbt** [comment]
Can I grab?

**Comment by fllprbt** [comment]
Well, that's why I never start an issue until it is assigned on me :) It is better though, to state your interest before starting/opening PRs so that nobody else tries to simultaneously do it.. (but as you see it does not always work)

You can proceed with your MR, I will find something else^^

**Comment by btzr-io** [comment]
@fllprbt sorry, I didn't have time to assign you the issue, if you don't see any comments or assigned user just leave a comment that you are working on it :v:
