### ISSUE TITLE
Ignore folders on publish

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#177]
This package only need the production bundle on the `dist` folder, the rest is used for development and testing. We should found a way to ignore the other folders every time the package is published.

**Comment by neckenth** [comment]
@btzr-io Can I take this on?

**Comment by btzr-io** [comment]
@neckenth sure, probably a `.npmignore` file will do the trick, see:
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by neckenth** [comment]
@btzr-io thank you! Would you be able to assign me to this issue?

In addition, would you mind please adding me as a collaborator so I can push up my branch and open a PR?

**Comment by btzr-io** [comment]
You should be able to push your branch from your forked repository.
