### ISSUE TITLE
About panel

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#18]
A panel or overlay container ( maybe even a pop up modal ) to display some info about the viwer:
- Logo / Project name
- Current version
- Description
- Maybe add the github links ?

**Comment by kamilszmajdzinski** [comment]
I am taking this one 🦹‍♂️

**Comment by kamilszmajdzinski** [comment]
https://github.com/btzr-io/Villain/pull/148

**Comment by btzr-io** [comment]
@kamilszmajdzinski Looks good :heart: 

- The logo image looks a little distorted (but we should probably change it to a svg)
- The modal component should have `accessibility`
-  That tooltip should be aligned to the center

I like the colors but I'm not sure if they are good for `accessibility` see: https://accessible-colors.com/
