### ISSUE TITLE
Use svg for the project logo

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#180]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jkvyff** [comment]
updated logo, but you may want to host the file in your own gist or at least maintain a copy.

**Comment by btzr-io** [comment]
@jkvyff Thanks but I'll work on this since I have the `svg` files,
Feel free to check other issues: https://github.com/btzr-io/Villain/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest
