### ISSUE TITLE
Hide tooltip on click

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#189]
The `tooltip` component should hide when the users clicks the button.

**Comment by shakti97** [comment]
Would like to work on this

**Comment by btzr-io** [comment]
@shakti97 sure

**Comment by Sonam3107** [comment]
Can I still take this up?

**Comment by btzr-io** [comment]
@Sonam3107 This requires knowledge on react and `reakit` https://reakit.io/, unless you going to start working on it right away I suggest you to look into other issues: 

https://github.com/btzr-io/Villain/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest

**Comment by Sonam3107** [comment]
Sure.

**Comment by btzr-io** [comment]
We don't use reakit  on V2.0.0
