### ISSUE TITLE
Online Community

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#192]
Create an online community to further discuss bugs, ideas and feedback.
please vote with a reaction:

- :+1:  Slack
- :heart: Discord
- :tada: Spectrum chat
- :thinking: Other ( leave a comment )

**Comment by negreirosleo** [comment]
I think Discord would be great, its easy and acessible :thinking:

**Comment by btzr-io** [comment]
Feel free to join the new Discord server:
https://discord.gg/CeuNsSd
