### ISSUE TITLE
Tooltip dont hide on dissabled button

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#196]
The `tooltip` don`t hide when the button is disabled, at least on Brave browser.

### Update
- Works fine on firefox.
- It should still work on disabled buttons, at least that's the intended behavior.

Please check: https://github.com/reakit/reakit/issues/471

**Comment by giubatt** [comment]
I'll work on this

**Comment by btzr-io** [comment]
![bravt](https://user-images.githubusercontent.com/14793624/67889611-6689d880-fb0c-11e9-962f-74cd23fcacf7.gif)
