### ISSUE TITLE
Slide transition for menu component

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#203]
Implement a way to have a slide transitions inside the menu component.

Please check this example to see the desired effect: https://codepen.io/btzr-io/pen/yVGGbY

Check the `youtube` player on a desktop browser for inspiration,

**Comment by felipebrunetti94** [comment]
Hello, can I take this one ?

**Comment by btzr-io** [comment]
@felipebrunetti94 we are using `reakit` for the menu components. please check the docs first:
https://reakit.io/

**Comment by felipebrunetti94** [comment]
just one question, the slider you refer is the slider where you move the frames ? and you want a frame preview just like in youtube ? Just to be sure...

**Comment by btzr-io** [comment]
@felipebrunetti94 No, the `menu` component (Settings) please check the examples mentioned.

**Comment by felipebrunetti94** [comment]
Now I got it kkk, sorry friend. Coding right now :D

**Comment by btzr-io** [comment]
Please check: https://reakit.io/docs/menu/
