### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#22]
Move the `npm` package ( villain-react component ) to its own folder.

**Comment by IsraelSampaio** [comment]
move the package.json?
what would the npm package be? 
could you give me more information?

**Comment by btzr-io** [comment]
@IsraelSampaio I mean to move it inside a folder something like "packages", see this example:
https://github.com/remarkjs/remark/tree/master/packages

I want to create a web-app that will use this package but they will exist in the same repo, this issue its probably complex due the current structure of the project.
This is probably not a good issue for you if you are a first time contributor to this project but feel free to give it a try.

**Comment by IsraelSampaio** [comment]
@btzr-io  are you talking about the lib folder? create a package folder with full-screen.js package?

**Comment by btzr-io** [comment]
I mean the `villain-react` component, see the example link of a monorepo ^^
