### ISSUE TITLE
Use more inclusive regexp for matching file paths

### ISSUE THREAD

**Issue by kauffj** [btzr-io/Villain#227]
Per this discussion over on lbry-desktop: https://github.com/lbryio/lbry-desktop/issues/2777#issuecomment-558000435

As long as you are in ES2018 or later land, you can use the capture group `\p{L}` to represent all letters and `\p{N}` all numbers. So you could use this (untested) regexp instead:

` /^[\p{L}\p{N}_@()-][\p{L}\p{N}_.@()-\s]+.(jpeg|jpg|png|bpm|webp)$/`

**Comment by btzr-io** [comment]
> Not supported in Firefox and Edge

> Despite being a part of the standard since 2018, unicode proeprties are not supported in Firefox (bug) and Edge (bug).

> There’s XRegExp library that provides “extended” regular expressions with cross-browser support for unicode properties.

Alternative: https://github.com/slevithan/xregexp

**Comment by btzr-io** [comment]
Looks like we can use this syntax directly with : 
https://github.com/josephfrazier/babel-plugin-transform-xregexp

**Comment by btzr-io** [comment]
It should be like this:
```
/^[\p{L}\p{N}_@()-]+[\p{L}\p{N}_.@()-]+.(jpeg|jpg|png|bpm|webp)$/u
```

**Comment by btzr-io** [comment]
Actually this is the correct regex with the unicode support:
https://github.com/btzr-io/Villain/blob/b133147f71ce145b089e1b4a359e3cbb65b5d773/src/lib/utils.js#L5-L7

**Comment by btzr-io** [comment]
See: https://github.com/nika-begiashvili/libarchivejs/issues/19
