### ISSUE TITLE
Ebooks integration

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#230]
What other formats should this support besides compressed archives ?

I think `epub` is a good option, `pdf` is also commonly used but it wont be a optimized for text content, just images.

### Possible solution
https://github.com/mozilla/pdf.js
https://github.com/futurepress/epub.js/

**Comment by DaniAcu** [comment]
I’m super excited to take it. Assign me if you want

**Comment by btzr-io** [comment]
@DaniAcu I'm not sure whats the right approach to handle this, or if is relevant to have internally, maybe create a plugin for this ?
https://github.com/btzr-io/Villain/issues/214

**Comment by DaniAcu** [comment]
Awesome. Let me spike that on this week and share some ideas about how start with that

**Comment by DaniAcu** [comment]
I tried many ideas and read a lot. So now I think that we could use a Factory. Check this sample and tell me if you are agree with that and I could start implementing that. https://sourcemaking.com/design_patterns/factory_method/java/1

**Comment by btzr-io** [comment]
@DaniAcu Looks interesting, sure feel free to open a PR, let me know if you have more questions or need any help :v:

**Comment by DaniAcu** [comment]
Thanks maybe if you have some documentation about how works the renderer or some overview could be helpful.

**Comment by btzr-io** [comment]
The render is just a react component for `openseadragon`
https://github.com/btzr-io/Villain/blob/master/packages/villain-react/src/components/render.js

**Comment by btzr-io** [comment]
@DaniAcu Hooks should help with this  #446

**Comment by DaniAcu** [comment]
I was looking into all the code. 
The first one is that all files that we are supporting, is support like image containers. Because on uncompress.js we are creating pages according to the image that we have on the Blob.
If we just support images, because that it's rendered just comics. It's fine and epub is already supported. But if we want to extend our reader to be used on books or other things. 
What it's the idea, we won't go to support another style of file or we are just supporting comics.

**Comment by btzr-io** [comment]
> It's fine and epub is already supported

Epub is not supported yet, thats why I open this issue to track development of more ebook formats like `epub` `pdf` etc...

**Comment by btzr-io** [comment]
The priority is to support comic-archive files, but if we could extend the support to other files / formats that will be great. Maybe as a plugin or extension if is not a viable option to add it in the main repo.

**Comment by btzr-io** [comment]
This definitely  should be a plugin or extension, not priority, I'll close this for now.
