### ISSUE TITLE
Load images

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#25]
Extend support to load an array of images instead of just compressed archives.

**Comment by DAMMAK** [comment]
can this be explain more.... i will love to handle it

**Comment by btzr-io** [comment]
Currently we load comic book archives and extract the images like this:
```JSX
<Villain file={'path/to/archive'} /> 
```

We should provide an option for already extracted files like this:

```JSX
<Villain files=['./image1.png', './image2.png', ...]
```

**Comment by btzr-io** [comment]
This is now implemented on  `v.2.0.0`
