### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#31]
We need some test to ensure everything is working fine :+1:

**Comment by btzr-io** [comment]
I mean like a unit testing for the react components.

**Comment by btzr-io** [comment]
Anyway this components has a complex structure so if you could just create a small test for a single component like a button or an input just to lead the way, that would be great :v:

**Comment by DaniAcu** [comment]
@btzr-io I could start setting the env to add tests with jest and create some test. If that it's okay for you, assign to me.

**Comment by btzr-io** [comment]
@DaniAcu sure, sounds good

@jenlky Are you working on this ?

**Comment by jenlky** [comment]
@btzr-io Nope

@DaniAcu Sure, go ahead!

**Comment by DaniAcu** [comment]
Well, the PR is there, tell me if you want to change something. Or need an explanation about something.
I'm happy to contribute with you on this repo :smile:

**Comment by btzr-io** [comment]
Thanks, I'm really new to tools like `jtest` but that pr looks good.
I'll tag you if I run into a problem, great work :v:
