### ISSUE TITLE
Implement shadow DOM

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#35]
We need to isolate the css styles of at least the toolbar component otherwise is easy to break  when having conflicts with the website styles.

Probably use a component for this or create a new one:
https://github.com/apearce/react-shadow-root
https://github.com/Wildhoney/ReactShadow#readme

**Comment by btzr-io** [comment]
See for more info: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM

**Comment by marcelorl** [comment]
taking this one

**Comment by btzr-io** [comment]
ok, go for it!

**Comment by btzr-io** [comment]
@marcelorl Let me know if you have any questions :v:

**Comment by btzr-io** [comment]
@marcelorl Are you still working on this ?

**Comment by marcelorl** [comment]
yes, still working

**Comment by marcelorl** [comment]
couldnt get it working.

not trying anymore, thanks.

**Comment by btzr-io** [comment]
I'm not sure this is relevant anymore
