### ISSUE TITLE
Mirror mode

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#36]
**Is your feature request related to a problem? Please describe.**
It should flip the images like a "mirror".

**Describe the solution you'd like**
`Openseadragon` provides this feature we just need a control to toggle it, see the docs for more info.

> Note always keep in mind usability and accessibility :v:

**Comment by TimeTerminal** [comment]
Hey, I'd like to take this one, but don't know how to properly set up the project locally 😅 

Once all packages are installed, I run `yarn start` and localhost opens up the Test Example. What's the next step after that?

<img width="768" alt="image" src="https://user-images.githubusercontent.com/10537934/67033188-26296400-f0e3-11e9-817a-2025b58eb4f7.png">

**Comment by btzr-io** [comment]
@TimeTerminal oh sorry, yeah we need better documentation about this.
You will need a comic book archive or just create a compressed archive with some images inside (zip, rar, tar....)

Change this with the location of your archive
https://github.com/btzr-io/Villain/blob/14ed9ca9497f39bfbf3d966bd45f3bcc3f3b3fb9/examples/index.js#L14

Can you open an issue about this?

**Comment by TimeTerminal** [comment]
Sweet, that worked! I tried opening an issue but can't click on the submit button. Perhaps a permissions issue?

**Comment by btzr-io** [comment]
@TimeTerminal idk how do I configure that (access to issues) ?

**Comment by TimeTerminal** [comment]
Not sure what happened, but #42 created.

**Comment by btzr-io** [comment]
@TimeTerminal nice thanks!

**Comment by TimeTerminal** [comment]
@btzr-io Just to confirm, in Book Mode the toggle should flip both images horizontally, yeah?

**Comment by btzr-io** [comment]
@TimeTerminal yes, not sure whats the usual behavior on this, I don't have any programs to test it
