### ISSUE TITLE
Improve message error 

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#37]
**Is your feature request related to a problem?**
The message error view needs some improvement.
Also we should improve the error message handler to detect different types of error.

**Comment by Joesepherus** [comment]
Can I work on this?

**Comment by btzr-io** [comment]
Did some progress on https://github.com/btzr-io/Villain/commit/3c056f0548ca008c3c116a9ddaa29849f1d9006e
Stil needs more work :upside_down_face:
