### ISSUE TITLE
Mobile compatibility

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#38]
Optimize viewer for mobile devices.

- [ ] Debounce zoom updates. See full conversation: https://github.com/btzr-io/Villain/pull/73#issuecomment-544680636

See related issue: https://github.com/btzr-io/Villain/issues/34

**Comment by HenriqueFadoni** [comment]
I am getting this issue

**Comment by HenriqueFadoni** [comment]
Could you better explain the problem?

**Comment by btzr-io** [comment]
Sorry this is unclear, but this is not a specific issue just means that you need to test it on mobile devices and find any stuff that don't work.

Feel free to report any issue and create a pull request if you find a solution.
