### ISSUE TITLE
Keyboard navigation for slider component

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#39]
**Is your feature request related to a problem?**

The current slider lags of a keyboard navigation, should probably be handled with arrow keys and mouse wheel if possible.

Related issue: https://github.com/btzr-io/Villain/issues/23

See for possible implementation: https://github.com/sghall/react-compound-slider/blob/master/docs/src/pages/slider-demos/horizontal/components.js#L106

**Comment by DaniAcu** [comment]
Fixed on this PR: https://github.com/btzr-io/Villain/pull/44
