### ISSUE TITLE
Slider component skipped key tab

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#40]
**Describe the bug**
The handler of the slider element don't auto focus when using key tab navigation.

**To Reproduce**
1. Press tab to navigate until you reach the toolbar controls (buttons)
4. See error ( slider don't get focus )

This will be probably required by: s://github.com/btzr-io/Villain/issues/39

**Comment by DaniAcu** [comment]
I want to contribute! I could take that issue, it's okay?

**Comment by btzr-io** [comment]
@DaniAcu sure go for it

**Comment by DaniAcu** [comment]
Awesome! So, fixed! https://github.com/btzr-io/Villain/pull/44
