### ISSUE TITLE
Keyboard-Only Focus Styles 

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#41]
**Is your feature request related to a problem? Please describe.**
Create keyboard-only foucs style for buttons and inputs.

**Describe the solution you'd like**
See for more info and examples:  https://css-tricks.com/keyboard-only-focus-styles/

**Comment by HenriqueFadoni** [comment]
I am getting this issue

**Comment by btzr-io** [comment]
@HenriqueFadoni Ok, please just pick one issue at a time

**Comment by btzr-io** [comment]
@HenriqueFadoni Are you working on this?

**Comment by btzr-io** [comment]
If you want to work on this issue please leave a comment.

**Comment by brkn** [comment]
Hi! I couldn't find a `browserlist`, which browser you would like to support?

**Comment by brkn** [comment]
I want to work on this issue by the way.

**Comment by btzr-io** [comment]
@brkn Hi, sorry for the late response, yeah looks like the css property posted on the link is not available yet on all browsers, not sure if there is alternative solution that can support more browsers.

> Hi! I couldn't find a browserlist, which browser you would like to support?
Thats a good idea, no there is no browser list ATM  is there any tools to test different browsers ? 

I think a priority is Firefox and chromium based browsers ( chrome, electron, brave )
I dont use `IE` or edge but it will be good to support it as well.

**Comment by btzr-io** [comment]
@brkn I think IE and edge are supported but I haven't do a proper test on those browsers, so idk

**Comment by brkn** [comment]
There is this tool: <browsersl.ist>.
You might want to check out this [article](https://css-tricks.com/browserlist-good-idea/) too!

I will investigate this issue further really soon. I'm not sure if there is a workaround for other browsers for that.
