### ISSUE TITLE
Improve documentation with development instructions

### ISSUE THREAD

**Issue by TimeTerminal** [btzr-io/Villain#42]
**Is your feature request related to a problem? Please describe.**
Documentation should provide the basic steps for contributors to get started with the project

**Describe the solution you'd like**
Contributors should be able to get started with ease

Related issue:  Improve documentation #16

**Comment by btzr-io** [comment]
Probably will be a good idea to include a small archive int the repository for quick testing

**Comment by TimeTerminal** [comment]
Sure, I can update my PR with a .zip file of 5-6 images.
