### ISSUE TITLE
Remove webpack usage

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#47]
Currently we use `webpack` to run the dev server and `rollup` to build the production module.
So we have two different config files and both are required to be on sync and be compatible with each other.

Is there anyway to just use `rollup` and discard `web-pack` ?

Well there is this,  but, web-pack has `react-hot-loader` implemented, so not sure if this is possible:
https://github.com/thgh/rollup-plugin-serve

**Comment by btzr-io** [comment]
Looks like rollup don't support HMR ? :upside_down_face:

**Comment by DaniAcu** [comment]
Maybe we could use rollup-plugin-server with rollup-plugin-livereload. What do you think?

**Comment by btzr-io** [comment]
@DaniAcu will it work well with react ?

**Comment by DaniAcu** [comment]
Let me try

**Comment by btzr-io** [comment]
@DaniAcu well if is efficient for development as the `webapck-dev` server go ahead, thanks :v:

**Comment by DaniAcu** [comment]
It's little tricky to do, but I will continue to research how to do

**Comment by btzr-io** [comment]
We now use nollup for v2.0.0 https://github.com/PepsRyuu/nollup
