### ISSUE TITLE
Use a better dev-server for testing

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#481]
**Describe the bug**
If we use create-react-app for the component playground demo and the web app it  should help keep things more simple and clean.

See https://github.com/btzr-io/Villain/issues/47

**Comment by mundane140** [comment]
Can work on this one.

**Comment by mundane140** [comment]
I'll need some directions. I can see that this is a mono repo and this will be my first time with monorepo. Should I just initialize my work as villian-cra in packages dir?

**Comment by btzr-io** [comment]
I created a react app that runs on the `webpack-dev` server to test the `villain-react` component,
I think this added unnecessary config files and dependencies and I want to keep this simple as possible:

Basically all you need to do is:
- Create a `create-react-app` inside the `villain-react` package directory, I suggest to keep the current name: `dev-sandbox`

- Move the contents of [villain-react/dev-sandbox](https://github.com/btzr-io/Villain/tree/master/packages/villain-react/dev-sandbox) to the `src` directory of the new `cra` . 

- Remove old config files and modules "webpack" etc...

**Comment by btzr-io** [comment]
For the web app, I just want to convert this to a `create-react-app`, I'm not sure exactly what changes will be require, but I don't think will be that easy 😛 

https://github.com/btzr-io/Villain/tree/master/packages/villain-web

**Comment by mundane140** [comment]
Hahahahahaha... Let me see what I can do. Its 4 am here and I am about to crash. I'll get back with some updates tomorrow.

**Comment by mundane140** [comment]
While copying files from `dev-sandbox` to `cra`, I noticed a `@/index.js` import statement. I have copied everything to the `cra/src`, have added import statements from the `index.js in dev-sandbox` to `index.js in cra`.

**Comment by btzr-io** [comment]
See: https://github.com/btzr-io/Villain/pull/538#issuecomment-675660864

**Comment by btzr-io** [comment]
I'm going to use nollup for the dev-server and remove any webpack usage: https://github.com/PepsRyuu/nollup
