### ISSUE TITLE
Broken example archive

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#49]
The example [archive](https://github.com/btzr-io/Villain/tree/master/build/testFile) included breaks the viewer when navigating from pages.

I suspect it contains corrupted images or unsupported format?
``` 
message: "Error loading image at blob:http://localhost:8080/2df85bc3-6f11-406e-9345-399c101a6bc0"
```

Also we should handle better this error: #37 

### Update

Well the issue appears to be related to this folder inside the archive: [`__MACOSX/`](https://superuser.com/a/104501)

All files contained in there had a valid extension name (png, jpg...) but invalid names (`._Name`), also from what I understand they are not real images so they will be handled as corrupted: 

```
Exampe.zip
--- ._Clouds.jpg
--- ._Sunset.jpg
--- ... 
```

So not sure if there is a way to ignore it?

**Comment by btzr-io** [comment]
@TimeTerminal Any ideas?

**Comment by btzr-io** [comment]
Here is the validation function used on the [uncompress](https://github.com/btzr-io/Villain/blob/master/src/components/uncompress.js) component: 

https://github.com/btzr-io/Villain/blob/2f596a4c4b37aa32623d01fe02f6d577bb2c785a/src/lib/utils.js#L14

**Comment by TimeTerminal** [comment]
Looks like it was the MacOS compression for zipping files. While on a Mac I didn't see a problem, switching to a Windows machine broke it. Creating a PR with a replacement archive.
