### ISSUE TITLE
Web-app

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#5]
Create a web application + embed api :rocket: 
- [x] Home page.
- [ ] Move docs to website ?
- [x] Initial UI for reader.
- [x] Get Domain #224 
- [x] Embed api
- [x] Open archive from local storage #239
- [ ] Document api
- [x] Drag and drop support: https://github.com/btzr-io/Villain/commit/c184f3a6a07b5ce2d21472971a6081503b020a3f

**Comment by btzr-io** [comment]
inital implementation on https://github.com/btzr-io/Villain/commit/f7f61b5c930f658eaaeecfd35aee1038dd7b4983

**Comment by btzr-io** [comment]
beta version live at: https://btzr-io.github.io/Villain/

**Comment by nika-begiashvili** [comment]
I think it would be great if you had sample comic book on live beta version

**Comment by btzr-io** [comment]
Drag and drop support: https://github.com/btzr-io/Villain/commit/c184f3a6a07b5ce2d21472971a6081503b020a3f
