### ISSUE TITLE
Rename workerPath option to workerUrl

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#55]
Rename `workerPath` to `workerUrl` to be consistent with `libarchive.js` api.

https://github.com/btzr-io/Villain/blob/b00ba2443d88702280470cf2f57f04ea7018e765/src/index.js#L15

Look for other definitions so index dont break after changes, also update `readme` and `changelog`.

**Comment by deniskond** [comment]
Hi, I can take this one :)

**Comment by btzr-io** [comment]
@deniskond sure, go for it

**Comment by btzr-io** [comment]
If some one else is working on this please leave a comment :v:

**Comment by btzr-io** [comment]
Anyway feel free to check more issues: https://github.com/btzr-io/Villain/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest
