### ISSUE TITLE
Split react component

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#6]
This repo host the web-app and also the react component version, it should be a good idea to organize the code in modules:

```
@Villain
--- @Villain/web-reader
--- @Villain/react-reader
```

**Comment by HenriqueFadoni** [comment]
Good idea, but what do you mean by modules? Fragment the components? Or just move it into folders?

**Comment by btzr-io** [comment]
@HenriqueFadoni I want to make a web app that uses the `villian-react` component so we will have two packages inside this repository:
```
Villain
--- ./villain-react
-- ./villain-web-app
```
,

**Comment by btzr-io** [comment]
See related issue: #5 #22

**Comment by DaniAcu** [comment]
If that it's the idea and if you think on create more components. May be we could move that to lerna. But it's only a thought
Check it https://github.com/lerna/lerna

**Comment by DaniAcu** [comment]
Or maybe Styleguidist. I only think on ways to do this more easy to check the sample and maintain the code. https://github.com/styleguidist/react-styleguidist

**Comment by btzr-io** [comment]
@DaniAcu Interesting, I'm also looking into: https://yarnpkg.com/lang/en/docs/workspaces/

But still unsure how to restructure the repo :thinking:

**Comment by btzr-io** [comment]
@DaniAcu I agree the example needs improvements ( my bad ) :upside_down_face: 

I was thinking about adding a form component to toggle all props and options of the viewer.

`Styleguidist` and `storybook` also looks like great integrations but I want to keep it simple as possible, at least for know.

Could you open an issue for this ?
