### ISSUE TITLE
Customizable toolbar

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#64]
Current set of options for toolbar is really limited, see https://github.com/btzr-io/Villain#options
We should provide and option to customize the toolbar elements.

## Possible solutions and ideas

- Create an `allowFeature..` props for each tool / feature 
- Create a prop to choose what toolbar actions will be shown:  `actions: ['fullscreen' , ...]`
- Maybe another one to block actions:  `blockActions: ['fullscreen',...]`
- Add custom buttons ? `buttons: [ { name: 'flip', action: (e) => something... } ]`

Open for suggestions.

**Comment by DaniAcu** [comment]
Maybe we could try with another pattern to be more reusable. For example, the final use could be...
<Villain>
<Villian.Button prop={value}></Villian.Button>
</Villian>
I don't know, how are some of the final cases that you are thinking, maybe if you could help me with vision or more context I could help with more robust ideas. :stuck_out_tongue_winking_eye:

**Comment by btzr-io** [comment]
I like that approach, not sure how easy will be to integrate due the current structure / state management.

**Comment by btzr-io** [comment]
Thanks to the new `hooks-api` it is now possible to make your own toolbar or any external component.
There still one provided as a default option.
