### ISSUE TITLE
Zoom handler event affects animations

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#66]
**Describe the bug**
The zoom handler function makes the zoom animations choppy and slow.
I suspect is caused by the new implentation on the `getTargetZoom` function.

**To Reproduce**
1. Use the wheel mouse button to zoom in / out.
2. See animations.

**Expected behavior**
Smooth zoom animations

https://github.com/btzr-io/Villain/blob/448b5594186876886c3ff9f654a40b82df3e6949/src/components/render.js#L165-L174

See: Optimize getTargetZoom function #67

**Comment by Brostafa** [comment]
@btzr-io https://github.com/btzr-io/Villain/pull/73/commits/34f5226beb2bf8bb4248712e547d048e6bb9fe71

**Comment by btzr-io** [comment]
## Update
The issue appears to be more noticeable on `firefox` I tested on chrome, brave and electron and its working really smooth.

**Comment by btzr-io** [comment]
Not sure if this is related: https://github.com/openseadragon/openseadragon/issues/1078

**Comment by btzr-io** [comment]
This require more work and testing.
