### ISSUE TITLE
Debounce resize handler

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#69]
Debounce the resize handler function on the `render` component,

https://github.com/btzr-io/Villain/blob/448b5594186876886c3ff9f654a40b82df3e6949/src/components/render.js#L161-L163

**Comment by Brostafa** [comment]
@btzr-io https://github.com/btzr-io/Villain/pull/70

**Comment by btzr-io** [comment]
I'm not sure if `debounce` is the right approach:
See full conversation: https://github.com/btzr-io/Villain/pull/70#issuecomment-544191138
