### ISSUE TITLE
Can't resolve 'reakit'

### ISSUE THREAD

**Issue by Daniil-Solovyev** [btzr-io/Villain#739]
Hello!
I am getting an error when running this script. Did anyone have the same problem? What am I doing wrong?

./node_modules/villain-react/dist/villain.js
Module not found: Can't resolve 'reakit' in '...reader\node_modules\villain-react\dist'

```
import React from "react"
import Villain from "villain-react"

import 'villain-react/dist/style.css'

const Reader = () => {
    const url = '~/archives/archive_5247_115849.cbr'
    const workerUrl="./libarchive.js/dist/worker-bundle.js"

    return <Villain source={url} workerUrl={workerUrl} />
}

export default Reader
```

**Comment by btzr-io** [comment]
@Daniil-Solovyev You need to include `reakit` as a dependency in your project. Is not included in build.
https://reakit.io/

**Comment by btzr-io** [comment]
I was working on version 2.0 ( It allows you to create a custom UI and some other improvements ) see: https://github.com/btzr-io/Villain/issues/634

But I'm not sure if this module is used enough to keep maintaining it.
Please let me know if you are interested on `v-2.0`.

**Comment by Daniil-Solovyev** [comment]
I include reakit.
Now my code is

```
import React from "react"
import Villain from "villain-react"

import 'villain-react/dist/style.css'

const Reader = () => {
    const url = '~/archives/archive_5247_115849.cbr'
    const workerUrl="~/node_modules/libarchive.js/dist/worker-bundle.js"

    return (
        <Villain source={url} workerUrl={workerUrl}/>
    )
}

export default Reader
```

And error

![Безымянный](https://user-images.githubusercontent.com/30840252/100656302-85851a80-335d-11eb-876f-d7438c72b3ec.png)

**Comment by btzr-io** [comment]
This files are going to be accessed by the browser so it needs to be an absolute path:
> Try to move this files to the public or static files directory in your server ( Usually where `index.html` is located )

Something like this
```
const url = 'http://localhost:3001/static/archives/archive_5247_115849.cbr'
const workerUrl="http://localhost:3001/static/js/worker-bundle.js"
```
Alternative: you can use an `iframe` to embed the reader.
See: https://villain.js.org/#/embed

**Comment by Daniil-Solovyev** [comment]
Ok. Than you.
