### ISSUE TITLE
Reduce messages text length

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#80]
Tooltip messages are too long to display properly we should simplify the text and make it clear to user.

Related issue: #78

**Comment by geekyrajshri** [comment]
Hey,
I can try this

**Comment by btzr-io** [comment]
@geekyrajshri There is already pr open for this: https://github.com/btzr-io/Villain/pull/82
If you think you can still improve it, please wait until gets merged

**Comment by btzr-io** [comment]
Closing this for now, leave a comment if this still need some changes
