### ISSUE TITLE
Improve example

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#81]
Example for testing needs improvement:

- [x] Add a form component to toggle all props and options of the viewer.
- [x] File input to choose any archive file on the computer.
- [ ] Fancy css styles are not required but really appreciated :v:

See full conversation: https://github.com/btzr-io/Villain/issues/6#issuecomment-544199351

**Comment by ismaeldcom** [comment]
I'm working on an initial *demo* component for the example. Still a lot of work to do but I want to discuss a question.

I implemented a *options parser* to create the form in a dynamic way using the default ones in state and avoid too much boilerplate when a new option is added. You'd like to continue with that or go for a manual declaration of the form?

The style will be improved, I only use a minimum of css for layout a space distribution.
![image](https://user-images.githubusercontent.com/7670276/67229397-869a0780-f43b-11e9-8e95-654ac837462b.png)

**Comment by btzr-io** [comment]
Dynamic is better ( great idea)
Awesome, looks really good! :+1:

**Comment by transitive-bullshit** [comment]
Would love to see a screenshot + hosted demo link featured prominently in the readme. Most of the time I want to just check out a project like this quickly before deciding whether or not I want to invest the time in reading the docs.

Great work!
