### ISSUE TITLE
Implement  internationalization / localization of strings

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#92]
We need component / api to handle localization of strings.

See possible solution: 
https://github.com/stefalda/react-localization/

## Update
- [x] `Setup react-localization`
- [x]  Wrap all strings inside the localization function.
- [x] Create option to set default locale ( language )  and control on context state.

**Comment by sprakash57** [comment]
Could you please assign this to me? i already have made some progress.

**Comment by btzr-io** [comment]
@sprakash57 sure
