### ISSUE TITLE
UI component to toggle manga mode ( reversed )

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#95]
Thanks to @maydayo for implementing the core logic of the `manga mode` on #87.
Now all we need is a simple button / check box to toggle this mode on the context state.

Please consider this other issues as well: #13 #34 

> Note always keep in mind usability and accessibility :v:

**Comment by quaj** [comment]
hi, what icon should use to this button?

**Comment by btzr-io** [comment]
@quaj Hi there is no more space on the toolbar to add new elements, we have to come with a solution `ASAP, see: #34 #13 

I don think there is a  clear icon to identify this, I think a check box with a label should do the job

**Comment by btzr-io** [comment]
@quaj But I'm open for suggestions, feel free to explore different ideas :v:

**Comment by quaj** [comment]
yep, i have tested and localize button has broken. Let me try other idea, what about static button?

**Comment by btzr-io** [comment]
>  localize button has broken
What do you mean? is it broken ?

**Comment by quaj** [comment]
ah my bad, i dont know how to describe that

the problem:
![image](https://user-images.githubusercontent.com/16853175/67263096-4dac7200-f4d1-11e9-831a-a531d086e665.png)

**Comment by btzr-io** [comment]
Oh Dont worry about that, as I said I think creating a menu or a solution for the lack of space on the toolbar should be priority but feel free to add it on the toolbar as long as is easy to migrate somewhere else :v:

**Comment by btzr-io** [comment]
@quaj just increase the width of the player, anyway I'll remove the language selector and move it somewhere else.

**Comment by btzr-io** [comment]
@quaj I don't read manga and also don't know how lol
Can you test it with a real manga archive and leave some feedback ?
Also what browser are you using  ( let me know if you run into any issues )?

**Comment by quaj** [comment]
yeah i'm using chrome and it's run pefect

i suggest language will depend from `navigator.language`, what do you think?

**Comment by quaj** [comment]
> @quaj I don't read manga and also don't know how lol
> Can you test it with a real manga archive and leave some feedback ?
> Also what browser are you using ( let me know if you run into any issues )?

I don't have any manga archive :cry:

**Comment by quaj** [comment]
@btzr-io check #114 pls

**Comment by btzr-io** [comment]
@quaj it should already auto detect the current user language ( uses navigator.language) , if is not working please open an issue.
