### ISSUE TITLE
Split main css into different files for each component

### ISSUE THREAD

**Issue by btzr-io** [btzr-io/Villain#99]
Currently all styles exists inside : https://github.com/btzr-io/Villain/blob/master/src/css/styles.css
We should create different files for each component:
```
- button.css
- tooltip.css
- ...
```

Also please see: Use post css for webpack and rollup #85

**Comment by geekyrajshri** [comment]
Can I take this up

**Comment by RamanaVem** [comment]
Hey @btzr-io  can i take a look on this?

**Comment by btzr-io** [comment]
@geekyrajshri sure

**Comment by btzr-io** [comment]
@RamanaVem feel free to look into other issues: https://github.com/btzr-io/Villain/issues

**Comment by btzr-io** [comment]
@geekyrajshri Are you still working on this ?

**Comment by RamanaVem** [comment]
@btzr-io i tried but am not able to setup locally your project if you have any simple html and css files as a modules you can share.

**Comment by geekyrajshri** [comment]
@btzr-io 
yup i am on it , will request a PR soon

**Comment by btzr-io** [comment]
@RamanaVem What is the problem, do you see any errors  ? Please open an issue so I can help

**Comment by RamanaVem** [comment]
Hey @btzr-io  i am new for YARN so could you help me.
![Screenshot_3](https://user-images.githubusercontent.com/56436577/67545477-d700b600-f716-11e9-9de4-8138b30d36fe.png)

just check what error am etting.
mailid: ramana.webdev@gmail.com

**Comment by btzr-io** [comment]
@RamanaVem you need to follow the `dev` instructions: first you need to run `yarn` to install the dependecies.

See: https://github.com/btzr-io/Villain#development

:warning:  Please open an issue to discuss this further so we don't spam this issue.
